### ISSUE TITLE
Move Delegates.* extension methods to sub package so they can be imported separately as a group

### ISSUE THREAD

**Issue by apatrida** [kohesive/injekt#1]
So that people do not tend to import `uy.kohesion.injekt.*` can move `Delegates` extension methods to `uy.kohesion.injekt.delegates` so that they can be imported from there as a whole and found as a group more easily.

**Comment by voddan** [comment]
Also it would make sense to use another grouping class instead of `Delegates`. 
I suggest `Injections`: 
      val log: Logger by Injections.injektLogger()

**Comment by apatrida** [comment]
Maybe, `Injections.logger()` ... I chose `Delegates` because that is where people are trained to look to delegate a property.   Will think on it.

**Comment by apatrida** [comment]
they are now top level to match Kotlin M13
