### ISSUE TITLE
Android project using injekt-core fails on dex task

### ISSUE THREAD

**Issue by b3er** [kohesive/injekt#8]
Android project using `injekt-core` can't be dexed because `InjektPackage.class` exists in `injekt-api` and `injekt-core` jars, and dexer can't merge multiple jars containing the same class files.

**Comment by apatrida** [comment]
Ok, fixing now and pushing a release.  Breaking change.  Moving the API classes to sub package api.

**Comment by apatrida** [comment]
Pushing release 1.2.0, should be available in 10-15 minutes on maven central.

**Comment by apatrida** [comment]
When you see it here, you can test: https://repo1.maven.org/maven2/uy/kohesive/injekt/injekt-core/

please let me know how it goes, I'd like to know that it works on Android

**Comment by apatrida** [comment]
1.2.0 is in maven central, ready for testing.

**Comment by apatrida** [comment]
Also, when done, if you have a simple android sample or test case I can add, that would be great.

**Comment by b3er** [comment]
Thanks! Working fine now. 
Created simple android app showing injekt basics: https://github.com/b3er/injekt-android-example
